<?php return array (
  'app_name' => 'BixBite',
  'app_url' => 'http://localhost/bixbite',
  'app_locale' => 'ru',
  'app_theme' => 'default',
  'app_skin' => 'default',
  'meta_title' => 'BixBite - Content Management System',
  'meta_title_delimiter' => ' — ',
  'meta_title_reverse' => '0',
  'meta_description' => 'BixBite - Content Management System',
  'meta_keywords' => 'BixBite CMS, BBCMS, CMS',
  'lock' => '1',
  'reason' => 'Upgrading Database! Retry later.',
  'retry' => '3600',
  'captcha_used' => '1',
  'captcha_width' => '68',
  'captcha_height' => '38',
  'captcha_font_family' => 'blowbrush',
  'captcha_font_size' => '20',
  'home_changefreq' => 'daily',
  'home_priority' => '0.9',
  'categories_changefreq' => 'daily',
  'categories_priority' => '0.6',
  'articles_changefreq' => 'daily',
  'articles_priority' => '0.4',
);